# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\lmomf\Desktop\is\Trabajo-grupal-IS\src\vista\ui\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiLoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(878, 800)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        MainWindow.setMaximumSize(QtCore.QSize(1300, 800))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0945274 rgba(235, 238, 242, 255), stop:1 rgb(8, 77, 166));\n"
"}")
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo_widget = QtWidgets.QFrame(self.central_widget)
        self.logo_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.logo_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.logo_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_widget.setObjectName("logo_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.logo_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_logo = QtWidgets.QLabel(self.logo_widget)
        self.lbl_logo.setMinimumSize(QtCore.QSize(150, 50))
        self.lbl_logo.setMaximumSize(QtCore.QSize(150, 50))
        self.lbl_logo.setText("")
        self.lbl_logo.setPixmap(QtGui.QPixmap("./src/vista/images/labtrack.png"))
        self.lbl_logo.setScaledContents(True)
        self.lbl_logo.setObjectName("lbl_logo")
        self.horizontalLayout.addWidget(self.lbl_logo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.logo_widget, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.login_widget = QtWidgets.QFrame(self.central_widget)
        self.login_widget.setStyleSheet("#login_widget {\n"
"    background-color: rgba(36, 37, 38, 50);\n"
"    border-radius: 20px\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(148, 157, 166);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.login_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_widget.setObjectName("login_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.login_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.login_body_widget = QtWidgets.QFrame(self.login_widget)
        self.login_body_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_body_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_body_widget.setObjectName("login_body_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.login_body_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_title = QtWidgets.QLabel(self.login_body_widget)
        self.lbl_title.setMinimumSize(QtCore.QSize(300, 50))
        self.lbl_title.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.lbl_title.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout_3.addWidget(self.lbl_title)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.user_widget = QtWidgets.QFrame(self.login_body_widget)
        self.user_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_widget.setObjectName("user_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.user_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_user = QtWidgets.QLabel(self.user_widget)
        self.lbl_user.setMinimumSize(QtCore.QSize(200, 30))
        self.lbl_user.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.lbl_user.setFont(font)
        self.lbl_user.setStyleSheet("QLabel {\n"
"    color: rgb(235, 238, 242);\n"
"}")
        self.lbl_user.setObjectName("lbl_user")
        self.verticalLayout_2.addWidget(self.lbl_user)
        self.input_user = QtWidgets.QLineEdit(self.user_widget)
        self.input_user.setMinimumSize(QtCore.QSize(200, 30))
        self.input_user.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(9)
        self.input_user.setFont(font)
        self.input_user.setStyleSheet("")
        self.input_user.setObjectName("input_user")
        self.verticalLayout_2.addWidget(self.input_user)
        self.verticalLayout_3.addWidget(self.user_widget, 0, QtCore.Qt.AlignHCenter)
        self.pass_widget = QtWidgets.QFrame(self.login_body_widget)
        self.pass_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pass_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pass_widget.setObjectName("pass_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pass_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_pass = QtWidgets.QLabel(self.pass_widget)
        self.lbl_pass.setMinimumSize(QtCore.QSize(200, 30))
        self.lbl_pass.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.lbl_pass.setFont(font)
        self.lbl_pass.setStyleSheet("QLabel {\n"
"    color: rgb(235, 238, 242);\n"
"}")
        self.lbl_pass.setObjectName("lbl_pass")
        self.verticalLayout_4.addWidget(self.lbl_pass)
        self.input_pass = QtWidgets.QLineEdit(self.pass_widget)
        self.input_pass.setMinimumSize(QtCore.QSize(200, 30))
        self.input_pass.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(9)
        self.input_pass.setFont(font)
        self.input_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_pass.setObjectName("input_pass")
        self.verticalLayout_4.addWidget(self.input_pass)
        self.verticalLayout_3.addWidget(self.pass_widget, 0, QtCore.Qt.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.btn_login = QtWidgets.QPushButton(self.login_body_widget)
        self.btn_login.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_login.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("QPushButton {\n"
"    border-radius: 4px;\n"
"    color: rgb(235, 238, 242);\n"
"    background-color: rgb(8, 77, 166);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(3, 90, 166);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"    color: rgb(8, 77, 166);\n"
"    background-color: rgb(235, 238, 242);\n"
"}")
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout_3.addWidget(self.btn_login, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2.addWidget(self.login_body_widget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.login_widget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_title.setText(_translate("MainWindow", "Inicio de sesión"))
        self.lbl_user.setText(_translate("MainWindow", "Usuario"))
        self.lbl_pass.setText(_translate("MainWindow", "Contraseña"))
        self.btn_login.setText(_translate("MainWindow", "Acceder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UiLoginWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
