# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\lmomf\Desktop\is\Trabajo-grupal-IS\src\vista\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1009, 547)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_bar = QtWidgets.QFrame(self.centralwidget)
        self.side_bar.setMinimumSize(QtCore.QSize(0, 0))
        self.side_bar.setMaximumSize(QtCore.QSize(150, 16777215))
        self.side_bar.setStyleSheet("")
        self.side_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_bar.setObjectName("side_bar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.side_bar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inventario_btn = QtWidgets.QPushButton(self.side_bar)
        self.inventario_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inventario_btn.sizePolicy().hasHeightForWidth())
        self.inventario_btn.setSizePolicy(sizePolicy)
        self.inventario_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.inventario_btn.setMaximumSize(QtCore.QSize(110, 110))
        self.inventario_btn.setStyleSheet("QPushButton {\n"
"    image: url(\"C:/Users/lmomf/Desktop/is/Trabajo-grupal-IS/src/vista/images/boton_inventario.png\") 0 0 0 0 stretch stretch;\n"
"    border-radius: 8px;\n"
"    color: rgb(235, 238, 242);\n"
"    background-color: rgb(8, 77, 166);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(3, 90, 166);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"    color: rgb(8, 77, 166);\n"
"    background-color: rgb(235, 238, 242);\n"
"}")
        self.inventario_btn.setText("")
        self.inventario_btn.setObjectName("inventario_btn")
        self.verticalLayout.addWidget(self.inventario_btn)
        self.maquinaria_btn = QtWidgets.QPushButton(self.side_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maquinaria_btn.sizePolicy().hasHeightForWidth())
        self.maquinaria_btn.setSizePolicy(sizePolicy)
        self.maquinaria_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.maquinaria_btn.setMaximumSize(QtCore.QSize(110, 110))
        self.maquinaria_btn.setStyleSheet("QPushButton {\n"
"    image: url(\"C:/Users/lmomf/Desktop/is/Trabajo-grupal-IS/src/vista/images/boton_maquinaria.png\") 0 0 0 0 stretch stretch;\n"
"    border-radius: 8px;\n"
"    color: rgb(235, 238, 242);\n"
"    background-color: rgb(8, 77, 166);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(3, 90, 166);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"    color: rgb(8, 77, 166);\n"
"    background-color: rgb(235, 238, 242);\n"
"}")
        self.maquinaria_btn.setText("")
        self.maquinaria_btn.setObjectName("maquinaria_btn")
        self.verticalLayout.addWidget(self.maquinaria_btn)
        self.panel_btn = QtWidgets.QPushButton(self.side_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel_btn.sizePolicy().hasHeightForWidth())
        self.panel_btn.setSizePolicy(sizePolicy)
        self.panel_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.panel_btn.setMaximumSize(QtCore.QSize(110, 110))
        self.panel_btn.setStyleSheet("QPushButton {\n"
"    image: url(\"C:/Users/lmomf/Desktop/is/Trabajo-grupal-IS/src/vista/images/boton_panel_colaborativo.png\") 0 0 0 0 stretch stretch;\n"
"    border-radius: 8px;\n"
"    color: rgb(235, 238, 242);\n"
"    background-color: rgb(8, 77, 166);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(3, 90, 166);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"    color: rgb(8, 77, 166);\n"
"    background-color: rgb(235, 238, 242);\n"
"}")
        self.panel_btn.setText("")
        self.panel_btn.setObjectName("panel_btn")
        self.verticalLayout.addWidget(self.panel_btn)
        self.proyecto_btn = QtWidgets.QPushButton(self.side_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proyecto_btn.sizePolicy().hasHeightForWidth())
        self.proyecto_btn.setSizePolicy(sizePolicy)
        self.proyecto_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.proyecto_btn.setMaximumSize(QtCore.QSize(110, 110))
        self.proyecto_btn.setStyleSheet("QPushButton {\n"
"    image: url(\"C:/Users/lmomf/Desktop/is/Trabajo-grupal-IS/src/vista/images/boton_proyecto.png\") 0 0 0 0 stretch stretch;\n"
"    border-radius: 8px;\n"
"    color: rgb(235, 238, 242);\n"
"    background-color: rgb(8, 77, 166);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(3, 90, 166);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"    color: rgb(8, 77, 166);\n"
"    background-color: rgb(235, 238, 242);\n"
"}")
        self.proyecto_btn.setText("")
        self.proyecto_btn.setObjectName("proyecto_btn")
        self.verticalLayout.addWidget(self.proyecto_btn)
        self.admin_btn = QtWidgets.QPushButton(self.side_bar)
        self.admin_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.admin_btn.sizePolicy().hasHeightForWidth())
        self.admin_btn.setSizePolicy(sizePolicy)
        self.admin_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.admin_btn.setMaximumSize(QtCore.QSize(110, 110))
        self.admin_btn.setStyleSheet("QPushButton {\n"
"    image: url(\"C:/Users/lmomf/Desktop/is/Trabajo-grupal-IS/src/vista/images/boton_admin.png\") 0 0 0 0 stretch stretch;\n"
"    border-radius: 8px;\n"
"    color: rgb(235, 238, 242);\n"
"    background-color: rgb(8, 77, 166);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(3, 90, 166);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"    color: rgb(8, 77, 166);\n"
"    background-color: rgb(235, 238, 242);\n"
"}")
        self.admin_btn.setText("")
        self.admin_btn.setObjectName("admin_btn")
        self.verticalLayout.addWidget(self.admin_btn)
        self.horizontalLayout.addWidget(self.side_bar)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.inventario_page = QtWidgets.QWidget()
        self.inventario_page.setEnabled(True)
        self.inventario_page.setObjectName("inventario_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.inventario_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titulo = QtWidgets.QLabel(self.inventario_page)
        self.titulo.setObjectName("titulo")
        self.verticalLayout_2.addWidget(self.titulo, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.busqueda_widget = QtWidgets.QFrame(self.inventario_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.busqueda_widget.sizePolicy().hasHeightForWidth())
        self.busqueda_widget.setSizePolicy(sizePolicy)
        self.busqueda_widget.setAutoFillBackground(False)
        self.busqueda_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.busqueda_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.busqueda_widget.setObjectName("busqueda_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.busqueda_widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bus_inventario_btn = QtWidgets.QPushButton(self.busqueda_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bus_inventario_btn.sizePolicy().hasHeightForWidth())
        self.bus_inventario_btn.setSizePolicy(sizePolicy)
        self.bus_inventario_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.bus_inventario_btn.setMaximumSize(QtCore.QSize(150, 50))
        self.bus_inventario_btn.setObjectName("bus_inventario_btn")
        self.horizontalLayout_3.addWidget(self.bus_inventario_btn)
        self.lineEdit = QtWidgets.QLineEdit(self.busqueda_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(800, 50))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.almacen_box = QtWidgets.QComboBox(self.busqueda_widget)
        self.almacen_box.setObjectName("almacen_box")
        self.horizontalLayout_3.addWidget(self.almacen_box)
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.busqueda_widget, 0, QtCore.Qt.AlignTop)
        self.tabla_inventario = QtWidgets.QTableWidget(self.inventario_page)
        self.tabla_inventario.setObjectName("tabla_inventario")
        self.tabla_inventario.setColumnCount(0)
        self.tabla_inventario.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tabla_inventario)
        self.stackedWidget.addWidget(self.inventario_page)
        self.maquinaria_page = QtWidgets.QWidget()
        self.maquinaria_page.setObjectName("maquinaria_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.maquinaria_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.titulo_2 = QtWidgets.QLabel(self.maquinaria_page)
        self.titulo_2.setObjectName("titulo_2")
        self.verticalLayout_3.addWidget(self.titulo_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.maquinaria_page)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bus_maquina_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bus_maquina_btn.sizePolicy().hasHeightForWidth())
        self.bus_maquina_btn.setSizePolicy(sizePolicy)
        self.bus_maquina_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.bus_maquina_btn.setMaximumSize(QtCore.QSize(150, 50))
        self.bus_maquina_btn.setObjectName("bus_maquina_btn")
        self.horizontalLayout_4.addWidget(self.bus_maquina_btn)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(800, 50))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_4.addWidget(self.lineEdit_2)
        self.almacen_box_2 = QtWidgets.QComboBox(self.frame)
        self.almacen_box_2.setObjectName("almacen_box_2")
        self.horizontalLayout_4.addWidget(self.almacen_box_2)
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.tabla_maquinaria = QtWidgets.QTableWidget(self.maquinaria_page)
        self.tabla_maquinaria.setObjectName("tabla_maquinaria")
        self.tabla_maquinaria.setColumnCount(0)
        self.tabla_maquinaria.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tabla_maquinaria)
        self.stackedWidget.addWidget(self.maquinaria_page)
        self.proyecto_page = QtWidgets.QWidget()
        self.proyecto_page.setObjectName("proyecto_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.proyecto_page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.titulo_3 = QtWidgets.QLabel(self.proyecto_page)
        self.titulo_3.setObjectName("titulo_3")
        self.verticalLayout_5.addWidget(self.titulo_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_3 = QtWidgets.QFrame(self.proyecto_page)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.subtitulo = QtWidgets.QLabel(self.frame_4)
        self.subtitulo.setObjectName("subtitulo")
        self.verticalLayout_4.addWidget(self.subtitulo, 0, QtCore.Qt.AlignHCenter)
        self.sol_materiales_btn = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sol_materiales_btn.sizePolicy().hasHeightForWidth())
        self.sol_materiales_btn.setSizePolicy(sizePolicy)
        self.sol_materiales_btn.setMinimumSize(QtCore.QSize(100, 100))
        self.sol_materiales_btn.setMaximumSize(QtCore.QSize(250, 250))
        self.sol_materiales_btn.setObjectName("sol_materiales_btn")
        self.verticalLayout_4.addWidget(self.sol_materiales_btn)
        self.sol_maquinaria_btn = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sol_maquinaria_btn.sizePolicy().hasHeightForWidth())
        self.sol_maquinaria_btn.setSizePolicy(sizePolicy)
        self.sol_maquinaria_btn.setMinimumSize(QtCore.QSize(100, 100))
        self.sol_maquinaria_btn.setMaximumSize(QtCore.QSize(250, 250))
        self.sol_maquinaria_btn.setObjectName("sol_maquinaria_btn")
        self.verticalLayout_4.addWidget(self.sol_maquinaria_btn)
        self.horizontalLayout_5.addWidget(self.frame_4)
        spacerItem3 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.tabla_miembros = QtWidgets.QTableWidget(self.frame_3)
        self.tabla_miembros.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabla_miembros.sizePolicy().hasHeightForWidth())
        self.tabla_miembros.setSizePolicy(sizePolicy)
        self.tabla_miembros.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.tabla_miembros.setObjectName("tabla_miembros")
        self.tabla_miembros.setColumnCount(0)
        self.tabla_miembros.setRowCount(0)
        self.horizontalLayout_5.addWidget(self.tabla_miembros)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.proyecto_page)
        self.panel_page = QtWidgets.QWidget()
        self.panel_page.setObjectName("panel_page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.panel_page)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.titulo_4 = QtWidgets.QLabel(self.panel_page)
        self.titulo_4.setObjectName("titulo_4")
        self.verticalLayout_9.addWidget(self.titulo_4, 0, QtCore.Qt.AlignHCenter)
        self.lista_panel = QtWidgets.QListWidget(self.panel_page)
        self.lista_panel.setObjectName("lista_panel")
        self.verticalLayout_9.addWidget(self.lista_panel)
        self.stackedWidget.addWidget(self.panel_page)
        self.admin_page = QtWidgets.QWidget()
        self.admin_page.setObjectName("admin_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.admin_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.title = QtWidgets.QLabel(self.admin_page)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.title.setObjectName("title")
        self.verticalLayout_6.addWidget(self.title, 0, QtCore.Qt.AlignHCenter)
        self.frame_7 = QtWidgets.QFrame(self.admin_page)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_6 = QtWidgets.QFrame(self.frame_7)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.subtitulo_3 = QtWidgets.QLabel(self.frame_6)
        self.subtitulo_3.setObjectName("subtitulo_3")
        self.verticalLayout_7.addWidget(self.subtitulo_3, 0, QtCore.Qt.AlignHCenter)
        self.tabla_copias = QtWidgets.QTableWidget(self.frame_6)
        self.tabla_copias.setObjectName("tabla_copias")
        self.tabla_copias.setColumnCount(0)
        self.tabla_copias.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tabla_copias)
        self.copia_sesguridad_btn = QtWidgets.QPushButton(self.frame_6)
        self.copia_sesguridad_btn.setObjectName("copia_sesguridad_btn")
        self.verticalLayout_7.addWidget(self.copia_sesguridad_btn)
        self.horizontalLayout_6.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.frame_7)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.subtitulo_2 = QtWidgets.QLabel(self.frame_5)
        self.subtitulo_2.setObjectName("subtitulo_2")
        self.verticalLayout_8.addWidget(self.subtitulo_2, 0, QtCore.Qt.AlignHCenter)
        self.lista_panel_2 = QtWidgets.QListView(self.frame_5)
        self.lista_panel_2.setObjectName("lista_panel_2")
        self.verticalLayout_8.addWidget(self.lista_panel_2)
        self.add_panel_btn = QtWidgets.QPushButton(self.frame_5)
        self.add_panel_btn.setObjectName("add_panel_btn")
        self.verticalLayout_8.addWidget(self.add_panel_btn)
        self.horizontalLayout_6.addWidget(self.frame_5)
        self.verticalLayout_6.addWidget(self.frame_7)
        self.stackedWidget.addWidget(self.admin_page)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titulo.setText(_translate("MainWindow", "Inventario"))
        self.bus_inventario_btn.setText(_translate("MainWindow", "Buscar en inventario"))
        self.titulo_2.setText(_translate("MainWindow", "Maquinaria"))
        self.bus_maquina_btn.setText(_translate("MainWindow", "Buscar en maquinaria"))
        self.titulo_3.setText(_translate("MainWindow", "Proyecto"))
        self.subtitulo.setText(_translate("MainWindow", "Solicitud de assets:"))
        self.sol_materiales_btn.setText(_translate("MainWindow", "Solicitar materiales"))
        self.sol_maquinaria_btn.setText(_translate("MainWindow", "Solicitar maquinaria"))
        self.titulo_4.setText(_translate("MainWindow", "Panel colaborativo"))
        self.title.setText(_translate("MainWindow", "Administración"))
        self.subtitulo_3.setText(_translate("MainWindow", "Copias de seguridad"))
        self.copia_sesguridad_btn.setText(_translate("MainWindow", "Crear copia de seguridad"))
        self.subtitulo_2.setText(_translate("MainWindow", "Entradas del panel colaborativo"))
        self.add_panel_btn.setText(_translate("MainWindow", "Añadir entrada al panel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
